spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/polytable
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: polytable
#    password: 1234

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: 'redisAdmin'

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: enter your email
    password: enter your password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  accessToken-validity-in-seconds: 3600 # 1시간
  refreshToken-validity-in-seconds: 18000 # 5시간

logging:
  level:
    me.hounds1: DEBUG

server:
  port: 9090